export enum ResponseCode{
  LINE_NOT_ACTIVE = '-1',
  DATABASE_QUERY = '-2',
  ICCID_INCORRECT = '-3',
  BIOGRAPHICAL_MODIFICATION = '-6',
  POSTPAGO_LINE = '-7',
  PORTABILITY_PROCESS = '-8',
  ERR_VALIDATE_USER_BSCS = '-9',
  MIN_HAS_CHANGES = '-10',
  ERR_DEACTIVATING_LINE = '-11',
  ERR_ICCID_CHANGE = '-12',
  ERR_VALIDATING_ICCID_STATUS = '-14',
  SIMCARD_STATUS_ERR = '-15',
  REQUIRED_PARAMETER = '-16',
  INCORRECT_ICCID_LENGTH = '-17',
  USER_BLOCKED = '-20',
  RECORDS_LEGALIZE = '-30',
  MIN_CHANGE_ERR = '-31',
  OPERATION_FAILED = '100',
  INPUT_PARAMETERS = '900',
  INVALID_PARAMETERS = '901',
  MAP_OUTPUT = '903',
  SERVICE_PROPERTIES = '904',
  PROCEDURE_CONSUMPTION_10 = '910',
  PROCEDURE_CONSUMPTION_11 = '911',
  PROCEDURE_CONSUMPTION_12 = '912',
  PROCEDURE_CONSUMPTION_13 = '913',
  PROCEDURE_CONSUMPTION_15 = '915',
  PROCEDURE_CONSUMPTION_16 = '916',
  PROCEDURE_CONSUMPTION_17 = '917',
  PROCEDURE_CONSUMPTION_18 = '918',
  PROCEDURE_CONSUMPTION_19 = '919'
}

export const ResponseCodeMessage = {
  [ResponseCode.LINE_NOT_ACTIVE]: 'La línea ingresada no se encuentra activada',
  [ResponseCode.DATABASE_QUERY]: 'No se pudo consultar la información, por favor inténtelo más tarde',
  [ResponseCode.ICCID_INCORRECT]: 'El número de sim card ingresado no es correcto. Por favor valide e inténtelo de nuevo',
  [ResponseCode.BIOGRAPHICAL_MODIFICATION]: 'La cuenta tuvo cambios demográficos en el último tiempo, para mayor información comuníquese con nuestros asesores en el *611',
  [ResponseCode.POSTPAGO_LINE]: 'La linea consultada es postpago y esta legalizada',
  [ResponseCode.PORTABILITY_PROCESS]: 'La línea se encuentra en proceso de portabilidad, para mayor información comuníquese con nuestros asesores en el *611',
  [ResponseCode.ERR_VALIDATE_USER_BSCS]: 'No se encontraron registros de los datos ingresados,  para mayor información comuníquese con nuestros asesores en el *611',
  [ResponseCode.MIN_HAS_CHANGES]: 'La cuenta tuvo cambios demográficos en el último tiempo, para mayor información comuníquese con nuestros asesores en el *611',
  [ResponseCode.ERR_DEACTIVATING_LINE]: 'No fue posible desactivar la línea, por favor inténtelo más',
  [ResponseCode.ERR_ICCID_CHANGE]: 'No fue posible realizar el cambio de sim card, por favor inténtelo más tarde',
  [ResponseCode.ERR_VALIDATING_ICCID_STATUS]: 'No fue posible validar el número de la sim card. Por favor inténtelo más tarde',
  [ResponseCode.SIMCARD_STATUS_ERR]: 'Valide el número de la sim card registrada e inténtelo nuevamente. Si el problema persiste comuníquese con nuestros asesores en el *611',
  [ResponseCode.REQUIRED_PARAMETER]: 'La información registrada no está completa. Por favor valide e inténtelo de nuevo',
  [ResponseCode.INCORRECT_ICCID_LENGTH]: 'La información registrada no es correcta. Por favor valide e inténtelo de nuevo',
  [ResponseCode.USER_BLOCKED]: 'No se pudo procesar la solicitud,  para mayor información comuníquese con nuestros asesores en el *611',
  [ResponseCode.RECORDS_LEGALIZE]: 'Los datos registrados no se encuentran legalizados, para mayor información comuníquese con nuestros asesores en el *611',
  [ResponseCode.MIN_CHANGE_ERR]: 'No fue posible realizar el cambio del número, por favor inténtelo más tarde',
  [ResponseCode.INPUT_PARAMETERS]: 'No fue posible realizar la consulta. Por favor valide los datos registrados',
  [ResponseCode.OPERATION_FAILED]: 'Error en la operacion MigrateSIMResource',
  [ResponseCode.INVALID_PARAMETERS]: 'No fue posible realizar la consulta. Por favor valide los datos registrados',
  [ResponseCode.MAP_OUTPUT]: 'No fue posible realizar la consulta. Por favor inténtelo más',
  [ResponseCode.SERVICE_PROPERTIES]: 'No fue posible realizar la consulta. Por favor inténtelo más tarde',
  [ResponseCode.PROCEDURE_CONSUMPTION_10]: 'No fue posible realizar la consulta. Por favor inténtelo más tarde',
  [ResponseCode.PROCEDURE_CONSUMPTION_11]: 'No fue posible realizar la consulta. Por favor inténtelo más tarde',
  [ResponseCode.PROCEDURE_CONSUMPTION_12]: 'No fue posible realizar la consulta. Por favor inténtelo más tarde',
  [ResponseCode.PROCEDURE_CONSUMPTION_13]: 'No fue posible realizar la consulta. Por favor inténtelo más tarde',
  [ResponseCode.PROCEDURE_CONSUMPTION_15]: 'No fue posible realizar la consulta. Por favor inténtelo más tarde',
  [ResponseCode.PROCEDURE_CONSUMPTION_16]: 'No fue posible realizar la consulta. Por favor inténtelo más tarde',
  [ResponseCode.PROCEDURE_CONSUMPTION_17]: 'No fue posible realizar la consulta. Por favor inténtelo más tarde',
  [ResponseCode.PROCEDURE_CONSUMPTION_18]: 'No fue posible realizar la consulta. Por favor inténtelo más tarde',
  [ResponseCode.PROCEDURE_CONSUMPTION_19]: 'No fue posible realizar la consulta. Por favor inténtelo más tarde'
}